defaults: &defaults
  appid: "wxjcqczh1xu86vmhoy"
  appsecret: "wxjcqczh1xu86vmhoy"
  access_token: "Btn0OmWUgl57qwksxazyXNjRrMLbBEUvJQ7bYWtngfDxeGNwLXzy4Z1j"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  appid: "wxcabc0cd7000f0d70"
  appsecret: "757b330edc8ead6e7f6d552c32a9cd1a"
