defaults: &defaults
  appid: "wxtqoiga49bbsmvyt7"
  appsecret: "jbywehxjxcdstqoosn1nhmieprqkffwl"
  access_token: "AwQdsht6ayVx4iHRBIpq0UlPWDEK7nyquf31xZHKUS0B4FYOR8IDGMLo"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  appid: "wxcabc0cd7000f0d70"
  appsecret: "757b330edc8ead6e7f6d552c32a9cd1a"
